name: Build and Push to GHCR

on:
  # Trigger action on push to the main/default branch or manual dispatch
  push:
    branches:
      - main
  workflow_dispatch:

env:
  UPDATER_PASS: ${{ secrets.UPDATER_PASS }}
  DEPLOYMENT_NAME: garage-deploy

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker container image
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest .

      # Push the Docker container image to GHCR
      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      - name: Update on server
        run: sleep 5 && curl https://updater.548b.ru/start_update -d "deployment_name=${DEPLOYMENT_NAME}&namespace=misis" -u "update:${UPDATER_PASS}"